name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install SDK deps
        working-directory: ./sdk
        run: npm ci
      - name: Build SDK (tsc)
        working-directory: ./sdk
        run: npm run build
      - name: Install Web UI deps
        working-directory: ./apps/web-ui
        run: npm ci
      - name: Build Web UI
        working-directory: ./apps/web-ui
        run: npm run build
